In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
x  = arr.copy()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
arr = np.array([1,2,3,4,5])
x  = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [6]:
arr1 = np.array([1,2,3])

for x in arr1:
    print(x)

1
2
3


In [7]:
arr2 = np.array([1,2,3,4])
arr3 = np.array([5,6,7,8])

arr4 = np.stack((arr2, arr3), axis = 1)

print(arr4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [8]:
arr2 = np.array([1,2,3,4])
arr3 = np.array([5,6,7,8])

arr4 = np.hstack((arr2, arr3))

print(arr4)

[1 2 3 4 5 6 7 8]


In [9]:
arr2 = np.array([1,2,3,4])
arr3 = np.array([5,6,7,8])

arr4 = np.dstack((arr2, arr3))

print(arr4)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [11]:
arr5 = np.array([1,2,3,4,5,6])
new_arr = np.array_split(arr5, 3)


print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[1 2]
[3 4]
[5 6]


In [13]:
arr6 = np.array([1,2,3,4,5,4,4])
x = np.where(arr6 == 4)

print(x)

(array([3, 5, 6]),)


In [14]:
arr6 = np.array([1,2,3,4,5,4,4])
x = np.where(arr6%2 == 0)

print(x)

(array([1, 3, 5, 6]),)


In [15]:
arr7 = np.array([6,7,8,9])
x = np.searchsorted(arr7,7)

print(x)

1


In [16]:
arr7 = np.array([6,7,8,9])
x = np.searchsorted(arr7,7, side = 'right')

print(x)

2


In [17]:
arr8 = np.array([1,3,5,7])

x1 = np.searchsorted(arr8, [2,4,6])

print(x1)

[1 2 3]


In [18]:
from numpy import random

x2 = random.randint(100, size=(5))
print(x2)

[87 63 84 76 90]


In [19]:
x2 = random.randint(100, size=(3,5))
print(x2)

[[64 28 84 45 40]
 [77 56 65 32 90]
 [61  5 54 28  6]]
