In [1]:
import numpy as np

In [26]:
a = np.array([1,2,3], dtype ="int32")
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get dimensions
a.ndim


1

In [9]:
b.ndim

2

In [12]:
a.shape

(3,)

In [13]:
b.shape

(2, 3)

In [18]:
a.dtype


dtype('int16')

In [28]:
# get size
a.itemsize

4

In [29]:
# Get total size
a.nbytes

12

In [32]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
#Get a specific element[r,c]
c[1, 5]

np.int64(13)

In [38]:
# Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
# Get a specific row
c[:,2]

array([ 3, 10])

In [41]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:-6:2]

array([], dtype=int64)

In [42]:
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [43]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
# GET SPECIFIC ELEMENT
d[0,1,1]

np.int64(4)

In [47]:
# replace
d[:,1,:] = [[9,9],[8,8]]

In [53]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [56]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [57]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [60]:
# Any other number 
np.full(a,4)


array([[[4, 4, 4],
        [4, 4, 4]]])

In [65]:
# Rnadom decimal numbers
np.random.rand(4,2,3)

array([[[0.87048942, 0.0965191 , 0.68376003],
        [0.5106678 , 0.21413368, 0.37989947]],

       [[0.87609734, 0.34409148, 0.3382554 ],
        [0.30171722, 0.30829216, 0.74967989]],

       [[0.79923357, 0.45948787, 0.83886269],
        [0.24831084, 0.28215897, 0.60232542]],

       [[0.57572281, 0.3020362 , 0.50789062],
        [0.72986146, 0.18203112, 0.17903941]]])

In [66]:
np.random.random_sample(a.shape)

array([0.64341829, 0.7083752 , 0.77009078])

In [73]:
# Random integer
np.random.randint(-4,7, size=(3,3))

array([[ 5, -3,  5],
       [-2,  1, -2],
       [-2,  3, -3]], dtype=int32)

In [74]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [87]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 100
b

array([100,   2,   3])

In [89]:
e = np.array([1,2,3,4])
print(e)

[1 2 3 4]


In [90]:
a += 2
a

array([3, 4, 5])

In [91]:
a -= 2
a

array([1, 2, 3])

In [92]:
a * 2
a

array([1, 2, 3])

In [93]:
a/2
a

array([1, 2, 3])

In [95]:
b = np.array([1,0,1,0])
e + b

array([2, 2, 4, 4])

In [96]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [100]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [101]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [103]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.min(stats)

np.int64(1)

In [106]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [107]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [110]:
v1 = np.array[(1,2,3,4)]
v2 = np.array[(5,6,7,8)]
np.vstack([v1,v2,v1,v2])

TypeError: 'builtin_function_or_method' object is not subscriptable