In [2]:
import numpy as np
import time

In [15]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)




1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


In [3]:
py_list = [1,2,3,4,5]
print("Multiplication", py_list*2)

np_array = np.array([1,2,3])
print("Multiplication", np_array*2)

start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_list =  np.arange(1000000)*2
print("\n Numpy operation time: ", time.time() - start)

Multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Multiplication [2 4 6]

 List operation time:  0.037854671478271484

 Numpy operation time:  0.0032684803009033203


In [17]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
full = np.full((2,2),7)
print(full)

[[7 7]
 [7 7]]


In [22]:
random = np.random.random((2,3))
print(random)

[[0.92055855 0.44826881 0.82770539]
 [0.59943156 0.55035303 0.56757871]]


In [23]:
sequence = np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


In [24]:
#Vector Matrix and Tensor

In [30]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#Properties

In [33]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data Type: ", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Data Type:  int64


In [34]:
#array Reshaping

In [43]:
arr = np.arange(12)
print("Original Array", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array", flattened)

raveled = reshaped.ravel()
print("\n Raveled array", raveled)

Transpose = reshaped.T
print("Transposed", Transpose)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
