In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With step",arr[1:8:2])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire column", arr_2d[:, 1])

Specific element 6
Entire row [4 5 6]
Entire row [2 5 8]


In [ ]:
### Sorting

In [ ]:
unsorted = np.array([3,1,4,5,6,7,2,8,9])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis = 1))

Sorted array [1 2 3 4 5 6 7 8 9]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


In [17]:
#Filtering

In [20]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number%2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


In [21]:
 #Filter with mask
mask = number > 5
print("Numbers greater than 5", number[mask])

Numbers greater than 5 [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [24]:
indices = [0,2,4]
print(number[indices])

where_result = np.where(number>5)
print(where_result)
print("NP where", number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [31]:
condition_array = np.where(number > 5, number, number)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
#Adding and removing data

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#combined = arr1 + arr2 ---- wrong 
#print(combined)

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


array compatibility


In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6,10])
c = np.array([7,8,9])
print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [41]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

with_new_column = np.array([[7],[8]])
with_new_column = np.hstack((original, with_new_column))
print("With new column", with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [42]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
